### ISSUE TITLE
Invalid code in the api documentation

### ISSUE THREAD

**Issue by Foine** [novius-os/documentation-api#3]
The real exemple in the sharable behaviours is not good.
You can't put function into the declaration of the $_behaviours array.
You must put it in a static function called _init()

Am I wrong ?

**Comment by Savageman** [comment]
Yes, it's a mistake.
Either use _init() or create a config file for your model.

**Comment by Savageman** [comment]
Thanks for the report, it's now fixed in 9a89af6681f2e541155a94080aba1b1ddd1da9f4
