### ISSUE TITLE
Invalid example on Behaviour Publishable

### ISSUE THREAD

**Issue by vrcAlbert** [novius-os/documentation-api#4]
Hi,

I recently tried to use the behaviour Publishable and found what appears to be a bug according to the documentation.

For this behaviour, you give 3 different ways of using it :
- On/Off state
- Date range
- The combinaison of the two above

I tried to use the second one, it did not work : Property "" not found for {Model}. I used the 3rd one instead. 

Is this a bug in documentation or in the API?

PS : I'm on current branch master/chiba, commit "a34bc96"

**Comment by Savageman** [comment]
Thanks, I'll check it soon.

**Comment by Savageman** [comment]
It was a bug in the documentation. Only 2 modes are available : yes/no state or date range (combined with the yes/no state which still remains).

I removed the wrong example from the documentation.
